### PR TITLE
fix logic errors due to operator precedence

### PR DESCRIPTION
**Pull request by fluxionary**
`not entity.name == "__builtin:item"` and the like will always return false.

### CODE REVIEW

**Comment by berengma** [comment]
You mean not is handled first ? like it should be with ~= like you did or the check for equal in paranthesis.

**Comment by fluxionary** [comment]
> You mean not is handled first ? like it should be with ~= like you did or the check for equal in paranthesis.

yes, `not entity.name == "__builtin:item"` is interpreted as `(not entity.name) == "__builtin:item"`.

**Comment by berengma** [comment]
Thanks for pointing this out. I will fix and test it.

**Comment by berengma** [comment]
fixed together with some other bugs

**Pull request closed without merging**
