### PR TITLE
Translation added.

### PR DESCRIPTION
**Pull request by acmgit**
Hello Gundul,
i added the Translation for your fishes ;-).
Greetings Clyde.

### CODE REVIEW

**Comment by berengma** [comment]
Thanks Clyde. But with minetest 5.0 the api uses an own clientside translation function: minetest.get_translator and minetest.translate. Wouldn't it be better to use the up to date function than the old intllib ?

**Comment by acmgit** [comment]
Of Course, you're right, but the intllib is only for backward compatibility, the inbuild to translate has priority. If neither inbuild or intllib is present, then it takes the original english text.Greetings, Clyde ;-).

Someday, i have to come 2 U. Enjoy your Time ... 

    On Saturday, October 31, 2020, 8:28:55 AM GMT+1, Gundul <notifications@github.com> wrote:  
 
 


Thanks Clyde. But with minetest 5.0 the api uses an own clientside translation function: minetest.get_translator and minetest.translate. Wouldn't it be better to use the up to date function than the old intllib ?

**Comment by berengma** [comment]
> Of Course, you're right, but the intllib is only for backward compatibility

water_life works only for minetest > 5.0
what exactly is the backward compatibility good for ?

**Comment by acmgit** [comment]
Good Question, i add it for the case of the cases ;-).
But right, in your case, you really don't need it.

**Pull request closed without merging**
